version: '3.7'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dbtravel
      - DB_USER=traveluser
      - DB_PASS=bobbiesi796
      - DEBUG=1

    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbtravel
      - POSTGRES_USER=traveluser
      - POSTGRES_PASSWORD=bobbiesi796

volumes:
  dev-db-data:
  dev-static-data:
