name: CI

on:
  push:
    branches: [develop]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
  test-lint:
    environment: dev
    needs: build
    steps:
      - name: Install dependencies
        run: python -m pip install -r requirements.dev.txt"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8 --no-color"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test --no-color"
