name: CI

on:
  push:
    branches: [develop, feature/*]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
  test-lint:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    env:
      SECRET_KEY: ${{ vars.SECRET_KEY }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_PORT: ${{ vars.DB_PORT }}
      DEBUG: ${{ vars.DEBUG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install -r requirements.dev.txt
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
