name: CI

on:
  push:
    branches: [develop, feature/*]

jobs:
  test-lint:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: python -m pip install -r requirements.dev.txt
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Lint
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASS: ${{ env.DB_PASS }}
          DB_PORT: ${{ env.DB_PORT }}
          DEBUG: ${{ env.DEBUG }}
        run: docker-compose run --rm app sh -c "flake8"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
